-- BiSTracker: Static data and shared constants

-- ============================================================
-- RUNTIME CONSTANTS
-- ============================================================

INSTANCES = {
    { key="ICC25", label="ICC 25", name="Icecrown Citadel",     difficulty=2, size=25 },
    { key="ICC10", label="ICC 10", name="Icecrown Citadel",     difficulty=1, size=10 },
    { key="RS25",  label="RS 25",  name="The Ruby Sanctum",     difficulty=2, size=25 },
    { key="RS10",  label="RS 10",  name="The Ruby Sanctum",     difficulty=1, size=10 },
    { key="TOC25", label="TOC 25", name="Trial of the Crusader",difficulty=2, size=25 },
    { key="TOC10", label="TOC 10", name="Trial of the Crusader",difficulty=1, size=10 },
}

GEAR_SLOTS = {
    { id=1,  name="Head"      }, { id=2,  name="Neck"      }, { id=3,  name="Shoulders" },
    { id=5,  name="Chest"     }, { id=6,  name="Waist"     }, { id=7,  name="Legs"      },
    { id=8,  name="Feet"      }, { id=9,  name="Wrist"     }, { id=10, name="Hands"     },
    { id=11, name="Ring 1"    }, { id=12, name="Ring 2"    },
    { id=13, name="Trinket 1" }, { id=14, name="Trinket 2" },
    { id=15, name="Back"      }, { id=16, name="Main Hand" }, { id=17, name="Off Hand"  },
    { id=18, name="Ranged"    },
}

RANGED_SLOTS = { Crossbow=true, Sigil=true, Idol=true, Totem=true, Libram=true, Wand=true, Ranged=true }
COL1_SLOTS   = { Head=true, Neck=true, Shoulders=true, Back=true, Chest=true, Wrist=true }
WEAPON_SLOTS = {
    ["Main Hand"]=true, ["Off Hand"]=true, Shield=true,
    Crossbow=true, Sigil=true, Idol=true, Totem=true, Libram=true, Wand=true, Ranged=true
}

-- GearScore (Mirrikat45 formula, ported from LibGearScore-1.0 for 3.3.5a).
-- Slot weight per equip location (GetItemInfo's itemEquipLoc string).
GS_SCALE    = 1.8618
GS_SLOT_MOD = {
    INVTYPE_RELIC=0.3164,          INVTYPE_TRINKET=0.5625,        INVTYPE_2HWEAPON=2.0,
    INVTYPE_WEAPONMAINHAND=1.0,    INVTYPE_WEAPONOFFHAND=1.0,     INVTYPE_RANGED=0.3164,
    INVTYPE_THROWN=0.3164,         INVTYPE_RANGEDRIGHT=0.3164,    INVTYPE_SHIELD=1.0,
    INVTYPE_WEAPON=1.0,            INVTYPE_HOLDABLE=1.0,          INVTYPE_HEAD=1.0,
    INVTYPE_NECK=0.5625,           INVTYPE_SHOULDER=0.75,         INVTYPE_CHEST=1.0,
    INVTYPE_ROBE=1.0,              INVTYPE_WAIST=0.75,            INVTYPE_LEGS=1.0,
    INVTYPE_FEET=0.75,             INVTYPE_WRIST=0.5625,          INVTYPE_HAND=0.75,
    INVTYPE_FINGER=0.5625,         INVTYPE_CLOAK=0.5625,          INVTYPE_BODY=0,
}
-- Per-rarity linear coefficients, split on item level 120.
GS_FORMULA = {
    A = { [4]={A=91.45, B=0.65},  [3]={A=81.375, B=0.8125}, [2]={A=73.0, B=1.0} },                       -- ilvl > 120
    B = { [4]={A=26.0,  B=1.2},   [3]={A=0.75,   B=1.8},    [2]={A=8.0,  B=2.0}, [1]={A=0.0, B=2.25} },  -- ilvl <= 120
}
-- Color gradient anchors for GetGearScoreColor(). Interpolated linearly between stops.
-- RGB components are 0-255 integers.
GS_COLOR_STOPS = {
    { gs=0,    r=154, g=154, b=154 },  -- Grey
    { gs=1000, r=255, g=255, b=255 },  -- White
    { gs=2000, r=30,  g=255, b=0   },  -- Green
    { gs=3000, r=0,   g=112, b=221 },  -- Blue
    { gs=4000, r=163, g=53,  b=238 },  -- Purple
    { gs=5000, r=255, g=128, b=0   },  -- Orange
    { gs=6000, r=255, g=100, b=100 },  -- Light Red
    { gs=6250, r=180, g=0,   b=0   },  -- Dark Red
}

DETAIL_LINE_H    = 14
DETAIL_COL_X     = { 5, 325 }
DETAIL_MAX_LINES = { 22, 24 }
ROW_H            = 22

CLASS_TREES = {
    DEATHKNIGHT = { "Blood DK Tank",       "Frost DK",           "Unholy DK",          "Blood DK Dps"        },
    WARRIOR      = { "Arms Warrior",        "Fury Warrior",       "Protection Warrior"  },
    PALADIN      = { "Holy Paladin",        "Protection Paladin", "Retribution Paladin" },
    ROGUE        = { "Assassination Rogue", "Combat Rogue",       "Subtlety Rogue"      },
    DRUID        = { "Balance Druid",       "Feral Combat Druid", "Restoration Druid"   },
    HUNTER       = { "Beast Mastery Hunter","Marksman Hunter",    "Survival Hunter"     },
    MAGE         = { "Arcane Mage",         "Fire Mage",          "Frost Mage"          },
    WARLOCK      = { "Affliction Warlock",  "Demonology Warlock", "Destruction Warlock" },
    PRIEST       = { "Discipline Priest",   "Holy Priest",        "Shadow Priest"       },
    SHAMAN       = { "Elemental Shaman",    "Enhancement Shaman", "Restoration Shaman", "Spellhance Shaman"   },
}

SPEC_COLORS = {
    ["Blood DK Tank"]="c41e3a", ["Unholy DK"]="c41e3a",       ["Frost DK"]="c41e3a",  ["Blood DK Dps"]="c41e3a",
    ["Fury Warrior"]="c69b6d",  ["Arms Warrior"]="c69b6d",    ["Protection Warrior"]="c69b6d",
    ["Holy Paladin"]="f48cba",  ["Protection Paladin"]="f48cba", ["Retribution Paladin"]="f48cba",
    ["Assassination Rogue"]="fff468", ["Combat Rogue"]="fff468", ["Subtlety Rogue"]="fff468",
    ["Balance Druid"]="ff7c0a", ["Feral Combat Druid"]="ff7c0a", ["Bear Druid"]="ff7c0a",
    ["Restoration Druid"]="ff7c0a",   ["Beast Mastery Hunter"]="abd473",
    ["Marksman Hunter"]="abd473", ["Survival Hunter"]="abd473",
    ["Arcane Mage"]="3fc7eb",   ["Fire Mage"]="3fc7eb",       ["Frost Mage"]="3fc7eb",
    ["Affliction Warlock"]="8788ee", ["Demonology Warlock"]="8788ee", ["Destruction Warlock"]="8788ee",
    ["Discipline Priest"]="f0ebe0", ["Holy Priest"]="f0ebe0", ["Shadow Priest"]="f0ebe0",
    ["Elemental Shaman"]="0070dd", ["Enhancement Shaman"]="0070dd",
    ["Restoration Shaman"]="0070dd", ["Spellhance Shaman"]="0070dd",
}

-- Shared secret for the export integrity checksum. Must match EXPORT_SECRET in the
-- spreadsheet's Apps Script EXACTLY (change in both, or imports will be rejected).
-- Note: the addon source is readable, so this only deters casual tampering.
EXPORT_SECRET = "BiSTrk!2026#warmane"

CLASS_ORDER = {
    "DEATHKNIGHT","WARRIOR","PALADIN","ROGUE","DRUID",
    "HUNTER","MAGE","WARLOCK","PRIEST","SHAMAN"
}

CLASS_LABELS = {
    DEATHKNIGHT="Death Knight", WARRIOR="Warrior",   PALADIN="Paladin",
    ROGUE="Rogue",              DRUID="Druid",        HUNTER="Hunter",
    MAGE="Mage",                WARLOCK="Warlock",    PRIEST="Priest",
    SHAMAN="Shaman",
}

COLOR = {
    -- Rarity
    uncommon  = "|cff1eff00",
    rare      = "|cff0070dd",
    epic      = "|cffa335ee",
    legendary = "|cffff8000",
    -- UI
    green     = "|cff44ff44",
    red       = "|cffff4444",
    blue      = "|cff00ccff",
    white     = "|cffffffff",
    lgrey     = "|cffc4c4c4",
    grey      = "|cff999999",
    dgrey     = "|cff333333",
    lorange   = "|cffffa759",
}

-- ============================================================
-- BiS ITEM DATA
-- ============================================================

ClassesBiS = {
    ["Blood DK Tank"] = {
        {slot="Head", bis={name="Broken Ram Skull Helm",ilvl=277}},
        {slot="Neck", bis={name="Bile-Encrusted Medallion",ilvl=277}, alt={name="Noose of Malachite",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Scourgelord Pauldrons",ilvl=277}},
        {slot="Back", bis={name="Royal Crimson Cloak",ilvl=277}, alt={name="Sentinel\'s Winter Cloak",ilvl=264}},
        {slot="Chest", bis={name="Sanctified Scourgelord Chestguard",ilvl=277}},
        {slot="Wrist", bis={name="Gargoyle Spit Bracers",ilvl=264}, alt={name="Bracers of Dark Reckoning",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Scourgelord Handguards",ilvl=277}},
        {slot="Waist", bis={name="Verdigris Chain Belt",ilvl=264}, alt={name="Belt of Broken Bones",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Scourgelord Legguards",ilvl=277}, alt={name="Legguards of Lost Hope",ilvl=277}},
        {slot="Feet", bis={name="Treads of Impending Resurrection",ilvl=284}, alt={name="Grinning Skull Greatboots",ilvl=277}},
        {slot="Ring", bis={name="Devium\'s Eternally Cold Ring",ilvl=277}},
        {slot="Ring", bis={name="Juggernaut Band",ilvl=277}, alt={name="Ashen Band of Endless Courage",ilvl=277}},
        {slot="Trinket", bis={name="Sindragosa\'s Flawless Fang",ilvl=277}},
        {slot="Trinket", bis={name="Petrified Twilight Scale",ilvl=284}, alt={name="Juggernaut\'s Vitality",ilvl=258}},
        {slot="Main Hand", bis={name="Shadowmourne",ilvl=284}, alt={name="Glorenzelg, High-Blade of the Silver Hand",ilvl=284}},
        {slot="Sigil", bis={name="Sigil of Insolence",ilvl=245}, alt={name="Sigil of the Frozen Conscience",ilvl=150}},
    },
    ["Unholy DK"] = {
        {slot="Head", bis={name="Sanctified Scourgelord Helmet",ilvl=277}},
        {slot="Neck", bis={name="Penumbra Pendant",ilvl=284}, alt={name="Ahn\'kahar Onyx Neckguard",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Scourgelord Shoulderplates",ilvl=277}},
        {slot="Back", bis={name="Winding Sheet",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Scourgelord Battleplate",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Polar Bear Claw Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Scourgelord Gauntlets",ilvl=277}},
        {slot="Waist", bis={name="Coldwraith Links",ilvl=277}},
        {slot="Legs", bis={name="Scourge Reaver\'s Legplates",ilvl=277}},
        {slot="Feet", bis={name="Apocalypse\'s Advance",ilvl=284}, alt={name="Blood-Soaked Saronite Stompers",ilvl=277}},
        {slot="Ring", bis={name="Might of Blight",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Might",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}, alt={name="Signet of Twilight",ilvl=284}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}, alt={name="Death\'s Choice",ilvl=258}},
        {slot="Main Hand", bis={name="Shadowmourne",ilvl=284}, alt={name="Glorenzelg, High-Blade of the Silver Hand",ilvl=284}},
        {slot="Sigil", bis={name="Sigil of the Hanged Man",ilvl=264}, alt={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
    },
    ["Blood DK Dps"] = {
        {slot="Head", bis={name="Sanctified Scourgelord Helmet",ilvl=277}},
        {slot="Neck", bis={name="Penumbra Pendant",ilvl=284}, alt={name="Ahn\'kahar Onyx Neckguard",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Scourgelord Shoulderplates",ilvl=277}},
        {slot="Back", bis={name="Winding Sheet",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Scourgelord Battleplate",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Polar Bear Claw Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Scourgelord Gauntlets",ilvl=277}},
        {slot="Waist", bis={name="Coldwraith Links",ilvl=277}},
        {slot="Legs", bis={name="Scourge Reaver\'s Legplates",ilvl=277}},
        {slot="Feet", bis={name="Apocalypse\'s Advance",ilvl=284}, alt={name="Blood-Soaked Saronite Stompers",ilvl=277}},
        {slot="Ring", bis={name="Might of Blight",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Might",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}, alt={name="Signet of Twilight",ilvl=284}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}, alt={name="Death\'s Choice",ilvl=258}},
        {slot="Main Hand", bis={name="Shadowmourne",ilvl=284}, alt={name="Glorenzelg, High-Blade of the Silver Hand",ilvl=284}},
        {slot="Sigil", bis={name="Sigil of the Hanged Man",ilvl=264}, alt={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
    },
    ["Frost DK"] = {
        {slot="Head", bis={name="Sanctified Scourgelord Helmet",ilvl=277}},
        {slot="Neck", bis={name="Penumbra Pendant",ilvl=284}, alt={name="Ahn\'kahar Onyx Neckguard",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Scourgelord Shoulderplates",ilvl=277}},
        {slot="Back", bis={name="Garrosh\'s Rage",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Scourgelord Battleplate",ilvl=277}},
        {slot="Wrist", bis={name="Toskk\'s Maximized Wristguards",ilvl=277}, alt={name="Polar Bear Claw Bracers",ilvl=277}},
        {slot="Hands", bis={name="Aldriana\'s Gloves of Secrecy",ilvl=277}},
        {slot="Waist", bis={name="Coldwraith Links",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Scourgelord Legplates",ilvl=277}},
        {slot="Feet", bis={name="Apocalypse\'s Advance",ilvl=284}, alt={name="Blood-Soaked Saronite Stompers",ilvl=277}},
        {slot="Ring", bis={name="Might of Blight",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Might",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
        {slot="Off Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
        {slot="Sigil", bis={name="Sigil of Awareness",ilvl=213}},
    },
    ["Fury Warrior"] = {
        {slot="Head", bis={name="Sanctified Ymirjar Lord\'s Helmet",ilvl=277}},
        {slot="Neck", bis={name="Penumbra Pendant",ilvl=284}, alt={name="Ahn\'kahar Onyx Neckguard",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Ymirjar Lord\'s Shoulderplates",ilvl=277}},
        {slot="Back", bis={name="Vereesa's Dexterity",ilvl=272}, alt={name="Shadowvault Slayer\'s Cloak",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Ymirjar Lord\'s Battleplate",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Toskk\'s Maximized Wristguards",ilvl=277}},
        {slot="Hands", bis={name="Aldriana\'s Gloves of Secrecy",ilvl=277}},
        {slot="Waist", bis={name="Coldwraith Links",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Ymirjar Lord\'s Legplates",ilvl=277}},
        {slot="Feet", bis={name="Apocalypse\'s Advance",ilvl=284}, alt={name="Blood-Soaked Saronite Stompers",ilvl=277}},
        {slot="Ring", bis={name="Frostbrood Sapphire Ring",ilvl=277}, alt={name="Signet of Twilight",ilvl=284}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Shadowmourne",ilvl=284}},
        {slot="Off Hand", bis={name="Glorenzelg, High-Blade of the Silver Hand",ilvl=284}},
        {slot="Crossbow", bis={name="Fal\'inrush, Defender of Quel\'thalas",ilvl=284}},
    },
    ["Protection Warrior"] = {
        {slot="Head", bis={name="Broken Ram Skull Helm",ilvl=277}},
        {slot="Neck", bis={name="Bile-Encrusted Medallion",ilvl=277}, alt={name="Noose of Malachite",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Ymirjar Lord\'s Pauldrons",ilvl=277}},
        {slot="Back", bis={name="Royal Crimson Cloak",ilvl=277}, alt={name="Sentinel\'s Winter Cloak",ilvl=264}},
        {slot="Chest", bis={name="Sanctified Ymirjar Lord\'s Breastplate",ilvl=277}},
        {slot="Wrist", bis={name="Gargoyle Spit Bracers",ilvl=264}, alt={name="Bracers of Dark Reckoning",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Ymirjar Lord\'s Handguards",ilvl=277}},
        {slot="Waist", bis={name="Verdigris Chain Belt",ilvl=264}, alt={name="Belt of Broken Bones",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Ymirjar Lord\'s Legguards",ilvl=277}},
        {slot="Feet", bis={name="Treads of Impending Resurrection",ilvl=284}, alt={name="Grinning Skull Greatboots",ilvl=277}},
        {slot="Ring", bis={name="Devium\'s Eternally Cold Ring",ilvl=277}},
        {slot="Ring", bis={name="Juggernaut Band",ilvl=277}, alt={name="Ashen Band of Endless Courage",ilvl=277}},
        {slot="Trinket", bis={name="Sindragosa\'s Flawless Fang",ilvl=277}},
        {slot="Trinket", bis={name="Petrified Twilight Scale",ilvl=284}, alt={name="Juggernaut\'s Vitality",ilvl=258}},
        {slot="Main Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}, alt={name="Mithrios, Bronzebeard\'s Legacy",ilvl=284}},
        {slot="Shield", bis={name="Icecrown Glacial Wall",ilvl=277}},
        {slot="Crossbow", bis={name="Dreamhunter\'s Carbine",ilvl=264}},
    },
    ["Retribution Paladin"] = {
        {slot="Head", bis={name="Sanctified Lightsworn Helmet",ilvl=277}},
        {slot="Neck", bis={name="Penumbra Pendant",ilvl=284}, alt={name="Ahn\'kahar Onyx Neckguard",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lightsworn Shoulderplates",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}, alt={name="Winding Sheet",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Lightsworn Battleplate",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Polar Bear Claw Bracers",ilvl=277}},
        {slot="Hands", bis={name="Anub\'ar Stalker\'s Gloves",ilvl=277}, alt={name="Fleshrending Gauntlets",ilvl=277}},
        {slot="Waist", bis={name="Astrylian\'s Sutured Cinch",ilvl=277}, alt={name="Nerub\'ar Stalker\'s Cord",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Lightsworn Legplates",ilvl=277}},
        {slot="Feet", bis={name="Apocalypse\'s Advance",ilvl=284}, alt={name="Blood-Soaked Saronite Stompers",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}, alt={name="Seal of Many Mouths",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}, alt={name="Frostbrood Sapphire Ring",ilvl=277}},
        {slot="Trinket", bis={name="Tiny Abomination in a Jar",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Shadowmourne",ilvl=284}, alt={name="Oathbinder, Charge of the Ranger-General",ilvl=284}},
        {slot="Libram", bis={name="Libram of Valiance",ilvl=245}, alt={name="Libram of Three Truths",ilvl=264}},
    },
    ["Protection Paladin"] = {
        {slot="Head", bis={name="Sanctified Lightsworn Faceguard",ilvl=277}, alt={name="Broken Ram Skull Helm",ilvl=277}},
        {slot="Neck", bis={name="Bile-Encrusted Medallion",ilvl=277}, alt={name="Noose of Malachite",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lightsworn Shoulderguards",ilvl=277}},
        {slot="Back", bis={name="Royal Crimson Cloak",ilvl=277}, alt={name="Sentinel\'s Winter Cloak",ilvl=264}},
        {slot="Chest", bis={name="Sanctified Lightsworn Chestguard",ilvl=277}},
        {slot="Wrist", bis={name="Gargoyle Spit Bracers",ilvl=264}, alt={name="Bracers of Dark Reckoning",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Lightsworn Handguards",ilvl=277}},
        {slot="Waist", bis={name="Verdigris Chain Belt",ilvl=264}, alt={name="Belt of Broken Bones",ilvl=277}},
        {slot="Legs", bis={name="Legguards of Lost Hope",ilvl=277}, alt={name="Sanctified Lightsworn Legguards",ilvl=277}},
        {slot="Feet", bis={name="Treads of Impending Resurrection",ilvl=284}, alt={name="Grinning Skull Greatboots",ilvl=277}},
        {slot="Ring", bis={name="Devium\'s Eternally Cold Ring",ilvl=277}},
        {slot="Ring", bis={name="Juggernaut Band",ilvl=277}, alt={name="Ashen Band of Endless Courage",ilvl=277}},
        {slot="Trinket", bis={name="Sindragosa\'s Flawless Fang",ilvl=277}},
        {slot="Trinket", bis={name="Petrified Twilight Scale",ilvl=284}, alt={name="Juggernaut\'s Vitality",ilvl=258}},
        {slot="Main Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}, alt={name="Mithrios, Bronzebeard\'s Legacy",ilvl=284}},
        {slot="Shield", bis={name="Icecrown Glacial Wall",ilvl=277}},
        {slot="Libram", bis={name="Libram of the Eternal Tower",ilvl=245}, alt={name="Libram of Valiance",ilvl=245}},
    },
    ["Holy Paladin"] = {
        {slot="Head", bis={name="Sanctified Lightsworn Headpiece",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Holiday\'s Grace",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lightsworn Spaulders",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Rot-Resistant Breastplate",ilvl=277}},
        {slot="Wrist", bis={name="Phaseshifter\'s Bracers",ilvl=284}},
        {slot="Hands", bis={name="Fallen Lord\'s Handguards",ilvl=277}},
        {slot="Waist", bis={name="Split Shape Belt",ilvl=284}, alt={name="Belt of the Blood Nova",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}, alt={name="Leggings of Dying Candles",ilvl=277}},
        {slot="Feet", bis={name="Foreshadow Steps",ilvl=284}, alt={name="Boots of the Funeral March",ilvl=277}},
        {slot="Ring", bis={name="Ring of Phased Regeneration",ilvl=284}, alt={name="Marrowgar\'s Frigid Eye",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Trinket", bis={name="Meteorite Crystal",ilvl=277}, alt={name="Solace of the Defeated",ilvl=258}},
        {slot="Trinket", bis={name="Glowing Twilight Scale",ilvl=284}, alt={name="Soul Preserver",ilvl=187}},
        {slot="Main Hand", bis={name="Val\'anyr, Hammer of Ancient Kings",ilvl=245}, alt={name="Bloodsurge, Kel\'Thuzad\'s Blade of Agony",ilvl=284}},
        {slot="Shield", bis={name="Bulwark of Smouldering Steel",ilvl=277}},
        {slot="Libram", bis={name="Libram of Renewal",ilvl=200}, alt={name="Libram of Veracity",ilvl=245}},
    },
    ["Combat Rogue"] = {
        {slot="Head", bis={name="Sanctified Shadowblade Helmet",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Shadowblade Pauldrons",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}, alt={name="Vereesa's Dexterity",ilvl=272}},
        {slot="Chest", bis={name="Ikfirus\'s Sack of Wonder",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Toskk\'s Maximized Wristguards",ilvl=277}},
        {slot="Hands", bis={name="Aldriana\'s Gloves of Secrecy",ilvl=277}},
        {slot="Waist", bis={name="Astrylian\'s Sutured Cinch",ilvl=277}},
        {slot="Legs", bis={name="Gangrenous Leggings",ilvl=277}},
        {slot="Feet", bis={name="Frostbitten Fur Boots",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}, alt={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Ring", bis={name="Frostbrood Sapphire Ring",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}, alt={name="Bloodvenom Blade",ilvl=277}},
        {slot="Off Hand", bis={name="Scourgeborne Waraxe",ilvl=277}},
        {slot="Crossbow", bis={name="Fal\'inrush, Defender of Quel\'thalas",ilvl=284}},
    },
    ["Assassination Rogue"] = {
        {slot="Head", bis={name="Geistlord\'s Punishment Sack",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Cultist\'s Bloodsoaked Spaulders",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}},
        {slot="Chest", bis={name="Ikfirus\'s Sack of Wonder",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}},
        {slot="Hands", bis={name="Sanctified Shadowblade Gauntlets",ilvl=277}},
        {slot="Waist", bis={name="Astrylian\'s Sutured Cinch",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Shadowblade Legplates",ilvl=277}},
        {slot="Feet", bis={name="Frostbitten Fur Boots",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}},
        {slot="Ring", bis={name="Band of the Bone Colossus",ilvl=277}},
        {slot="Trinket", bis={name="Tiny Abomination in a Jar",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Heaven\'s Fall, Kryss of a Thousand Lies",ilvl=284}},
        {slot="Off Hand", bis={name="Lungbreaker",ilvl=277}},
        {slot="Crossbow", bis={name="Fal\'inrush, Defender of Quel\'thalas",ilvl=284}},
    },
    ["Feral Combat Druid"] = {
        {slot="Head", bis={name="Sanctified Lasherweave Headguard",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lasherweave Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}, alt={name="Vereesa's Dexterity",ilvl=272}},
        {slot="Chest", bis={name="Sanctified Lasherweave Raiment",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Toskk\'s Maximized Wristguards",ilvl=277}},
        {slot="Hands", bis={name="Aldriana\'s Gloves of Secrecy",ilvl=277}},
        {slot="Waist", bis={name="Astrylian\'s Sutured Cinch",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Lasherweave Legguards",ilvl=277}},
        {slot="Feet", bis={name="Frostbitten Fur Boots",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}, alt={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Ring", bis={name="Band of the Bone Colossus",ilvl=277}, alt={name="Frostbrood Sapphire Ring",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Oathbinder, Charge of the Ranger-General",ilvl=284}},
        {slot="Idol", bis={name="Idol of the Crying Moon",ilvl=264}},
    },
    ["Bear Druid"] = {
        {slot="Head", bis={name="Sanctified Lasherweave Headguard",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lasherweave Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}, alt={name="Vereesa's Dexterity",ilvl=272}},
        {slot="Chest", bis={name="Sanctified Lasherweave Raiment",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Toskk\'s Maximized Wristguards",ilvl=277}},
        {slot="Hands", bis={name="Aldriana\'s Gloves of Secrecy",ilvl=277}},
        {slot="Waist", bis={name="Astrylian\'s Sutured Cinch",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Lasherweave Legguards",ilvl=277}},
        {slot="Feet", bis={name="Frostbitten Fur Boots",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}, alt={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Ring", bis={name="Band of the Bone Colossus",ilvl=277}, alt={name="Frostbrood Sapphire Ring",ilvl=277}},
        {slot="Trinket", bis={name="Sindragosa\'s Flawless Fang",ilvl=277}},
        {slot="Trinket", bis={name="Juggernaut\'s Vitality",ilvl=258}},
        {slot="Main Hand", bis={name="Oathbinder, Charge of the Ranger-General",ilvl=284}},
        {slot="Idol", bis={name="Idol of the Crying Moon",ilvl=264}},
    },
    ["Balance Druid"] = {
        {slot="Head", bis={name="Sanctified Lasherweave Cover",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lasherweave Mantle",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Lasherweave Vestment",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Lasherweave Gloves",ilvl=277}, alt={name="Gunship Captain\'s Mittens",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Idol", bis={name="Idol of the Lunar Eclipse",ilvl=264}},
    },
    ["Restoration Druid"] = {
        {slot="Head", bis={name="Sanctified Lasherweave Helmet",ilvl=277}},
        {slot="Neck", bis={name="Bone Sentinel\'s Amulet",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Lasherweave Pauldrons",ilvl=277}},
        {slot="Back", bis={name="Greatcloak of the Turned Champion",ilvl=277}},
        {slot="Chest", bis={name="Sanguine Silk Robes",ilvl=277}},
        {slot="Wrist", bis={name="Phaseshifter\'s Bracers",ilvl=284}, alt={name="Bracers of Eternal Dreaming",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Lasherweave Gauntlets",ilvl=277}, alt={name="Handguards of Winter\'s Respite",ilvl=277}},
        {slot="Waist", bis={name="Professor\'s Bloodied Smock",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Lasherweave Legplates",ilvl=277}},
        {slot="Feet", bis={name="Boots of Unnatural Growth",ilvl=277}, alt={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Memory of Malygos",ilvl=277}, alt={name="Ashen Band of Endless Wisdom",ilvl=277}},
        {slot="Ring", bis={name="Ring of Phased Regeneration",ilvl=284}},
        {slot="Trinket", bis={name="Althor\'s Abacus",ilvl=277}, alt={name="Solace of the Defeated",ilvl=258}},
        {slot="Trinket", bis={name="Glowing Twilight Scale",ilvl=284}, alt={name="Soul Preserver",ilvl=187}},
        {slot="Main Hand", bis={name="Val\'anyr, Hammer of Ancient Kings",ilvl=245}, alt={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Sundial of Eternal Dusk",ilvl=277}, alt={name="Trauma",ilvl=277}},
        {slot="Idol", bis={name="Idol of the Black Willow",ilvl=264}},
    },
    ["Marksman Hunter"] = {
        {slot="Head", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Headpiece",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Spaulders",ilvl=277}},
        {slot="Back", bis={name="Vereesa's Dexterity",ilvl=272}, alt={name="Shadowvault Slayer\'s Cloak",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Tunic",ilvl=277}},
        {slot="Wrist", bis={name="Scourge Hunter\'s Vambraces",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Handguards",ilvl=277}},
        {slot="Waist", bis={name="Nerub\'ar Stalker\'s Cord",ilvl=277}},
        {slot="Legs", bis={name="Leggings of Northern Lights",ilvl=277}},
        {slot="Feet", bis={name="Returning Footfalls",ilvl=284}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}, alt={name="Signet of Twilight",ilvl=284}},
        {slot="Ring", bis={name="Frostbrood Sapphire Ring",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Oathbinder, Charge of the Ranger-General",ilvl=284}},
        {slot="Crossbow", bis={name="Fal\'inrush, Defender of Quel\'thalas",ilvl=284}, alt={name="Zod\'s Repeating Longbow",ilvl=277}},
    },
    ["Survival Hunter"] = {
        {slot="Head", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Headpiece",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Spaulders",ilvl=277}},
        {slot="Back", bis={name="Vereesa's Dexterity",ilvl=272}, alt={name="Shadowvault Slayer\'s Cloak",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Tunic",ilvl=277}},
        {slot="Wrist", bis={name="Scourge Hunter\'s Vambraces",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Ahn\'Kahar Blood Hunter\'s Handguards",ilvl=277}},
        {slot="Waist", bis={name="Nerub\'ar Stalker\'s Cord",ilvl=277}},
        {slot="Legs", bis={name="Leggings of Northern Lights",ilvl=277}},
        {slot="Feet", bis={name="Returning Footfalls",ilvl=284}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Oathbinder, Charge of the Ranger-General",ilvl=284}},
        {slot="Crossbow", bis={name="Fal\'inrush, Defender of Quel\'thalas",ilvl=284}, alt={name="Zod\'s Repeating Longbow",ilvl=277}},
    },
    ["Fire Mage"] = {
        {slot="Head", bis={name="Sanctified Bloodmage Hood",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Bloodmage Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Robe of the Waking Nightmare",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Bloodmage Gloves",ilvl=277}, alt={name="Gunship Captain\'s Mittens",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}, alt={name="Lingering Illness",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Bloodmage Leggings",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Main Hand", bis={name="Bloodsurge, Kel\'Thuzad\'s Blade of Agony",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Arcane Mage"] = {
        {slot="Head", bis={name="Sanctified Bloodmage Hood",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Bloodmage Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Bloodmage Robe",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Bloodmage Gloves",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Bloodsurge, Kel\'Thuzad\'s Blade of Agony",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Demonology Warlock"] = {
        {slot="Head", bis={name="Sanctified Dark Coven Hood",ilvl=277}},
        {slot="Neck", bis={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Dark Coven Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Dark Coven Robe",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Dark Coven Gloves",ilvl=277}, alt={name="Gunship Captain\'s Mittens",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}, alt={name="Lingering Illness",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Bloodsurge, Kel\'Thuzad\'s Blade of Agony",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Affliction Warlock"] = {
        {slot="Head", bis={name="Sanctified Dark Coven Hood",ilvl=277}},
        {slot="Neck", bis={name="Amulet of the Silent Eulogy",ilvl=277}, alt={name="Blood Queen\'s Crimson Choker",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Dark Coven Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Dark Coven Robe",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Dark Coven Gloves",ilvl=277}, alt={name="Gunship Captain\'s Mittens",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Bloodsurge, Kel\'Thuzad\'s Blade of Agony",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Shadow Priest"] = {
        {slot="Head", bis={name="Sanctified Crimson Acolyte Cowl",ilvl=277}},
        {slot="Neck", bis={name="Amulet of the Silent Eulogy",ilvl=277}, alt={name="Blood Queen\'s Crimson Choker",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Crimson Acolyte Mantle",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Crimson Acolyte Raiments",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="The Lady\'s Brittle Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Crimson Acolyte Handwraps",ilvl=277}, alt={name="Gunship Captain\'s Mittens",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Plaguebringer\'s Stained Pants",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Holy Priest"] = {
        {slot="Head", bis={name="Sanctified Crimson Acolyte Hood",ilvl=277}},
        {slot="Neck", bis={name="Bone Sentinel\'s Amulet",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Crimson Acolyte Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Greatcloak of the Turned Champion",ilvl=277}},
        {slot="Chest", bis={name="Sanguine Silk Robes",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="Death Surgeon\'s Sleeves",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Crimson Acolyte Gloves",ilvl=277}},
        {slot="Waist", bis={name="Lingering Illness",ilvl=277}, alt={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Crimson Acolyte Leggings",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Memory of Malygos",ilvl=277}},
        {slot="Ring", bis={name="Ring of Phased Regeneration",ilvl=284}},
        {slot="Trinket", bis={name="Althor\'s Abacus",ilvl=277}, alt={name="Solace of the Defeated",ilvl=258}},
        {slot="Trinket", bis={name="Glowing Twilight Scale",ilvl=284}, alt={name="Soul Preserver",ilvl=187}},
        {slot="Main Hand", bis={name="Val\'anyr, Hammer of Ancient Kings",ilvl=245}, alt={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Sundial of Eternal Dusk",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}, alt={name="Nightmare Ender",ilvl=277}},
    },
    ["Discipline Priest"] = {
        {slot="Head", bis={name="Sanctified Crimson Acolyte Hood",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Holiday\'s Grace",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Crimson Acolyte Shoulderpads",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Crimson Acolyte Raiments",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="Death Surgeon\'s Sleeves",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Crimson Acolyte Gloves",ilvl=277}, alt={name="San\'layn Ritualist Gloves",ilvl=277}},
        {slot="Waist", bis={name="Crushing Coldwraith Belt",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Crimson Acolyte Leggings",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}},
        {slot="Ring", bis={name="Ring of Phased Regeneration",ilvl=284}},
        {slot="Trinket", bis={name="Althor\'s Abacus",ilvl=277}},
        {slot="Trinket", bis={name="Glowing Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Shadow Silk Spindle",ilvl=277}},
        {slot="Wand", bis={name="Corpse-Impaling Spike",ilvl=277}},
    },
    ["Restoration Shaman"] = {
        {slot="Head", bis={name="Sanctified Frost Witch\'s Headpiece",ilvl=277}, alt={name="Snowstorm Helm",ilvl=277}},
        {slot="Neck", bis={name="Blood Queen\'s Crimson Choker",ilvl=277}, alt={name="Holiday\'s Grace",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Frost Witch\'s Spaulders",ilvl=277}, alt={name="Horrific Flesh Epaulets",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Frost Witch\'s Tunic",ilvl=277}, alt={name="Mail of Crimson Coins",ilvl=277}},
        {slot="Wrist", bis={name="Phaseshifter\'s Bracers",ilvl=284}, alt={name="Bloodsunder\'s Bracers",ilvl=277}},
        {slot="Hands", bis={name="Changeling Gloves",ilvl=277}, alt={name="Unclean Surgical Gloves",ilvl=277}},
        {slot="Waist", bis={name="Split Shape Belt",ilvl=284}, alt={name="Belt of the Blood Nova",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Frost Witch\'s Legguards",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}, alt={name="Necrophotic Greaves",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Ashen Band of Endless Wisdom",ilvl=277}},
        {slot="Ring", bis={name="Ring of Phased Regeneration",ilvl=284}, alt={name="Marrowgar\'s Frigid Eye",ilvl=277}},
        {slot="Trinket", bis={name="Solace of the Defeated",ilvl=258}, alt={name="Soul Preserver",ilvl=187}},
        {slot="Trinket", bis={name="Glowing Twilight Scale",ilvl=284}, alt={name="Althor\'s Abacus",ilvl=277}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}, alt={name="Val\'anyr, Hammer of Ancient Kings",ilvl=245}},
        {slot="Shield", bis={name="Bulwark of Smouldering Steel",ilvl=277}},
        {slot="Totem", bis={name="Totem of the Surging Sea",ilvl=264}, alt={name="Totem of Calming Tides",ilvl=245}},
    },
    ["Elemental Shaman"] = {
        {slot="Head", bis={name="Sanctified Frost Witch\'s Helm",ilvl=277}, alt={name="Snowstorm Helm",ilvl=277}},
        {slot="Neck", bis={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Frost Witch\'s Shoulderpads",ilvl=277}, alt={name="Horrific Flesh Epaulets",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}, alt={name="Frostbinder\'s Shredded Cape",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Frost Witch\'s Hauberk",ilvl=277}},
        {slot="Wrist", bis={name="Bracers of Fiery Night",ilvl=284}, alt={name="Bloodsunder\'s Bracers",ilvl=277}},
        {slot="Hands", bis={name="Sanctified Frost Witch\'s Gloves",ilvl=277}},
        {slot="Waist", bis={name="Split Shape Belt",ilvl=284}, alt={name="Belt of the Blood Nova",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Frost Witch\'s Kilt",ilvl=277}},
        {slot="Feet", bis={name="Plague Scientist\'s Boots",ilvl=277}, alt={name="Necrophotic Greaves",ilvl=277}},
        {slot="Ring", bis={name="Ring of Rapid Ascent",ilvl=277}, alt={name="Valanar\'s Other Signet Ring",ilvl=277}},
        {slot="Ring", bis={name="Ashen Band of Endless Destruction",ilvl=277}},
        {slot="Trinket", bis={name="Phylactery of the Nameless Lich",ilvl=277}, alt={name="Dislodged Foreign Object",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Shield", bis={name="Bulwark of Smouldering Steel",ilvl=277}},
        {slot="Totem", bis={name="Totem of Hex",ilvl=213}},
    },
    ["Enhancement Shaman"] = {
        {slot="Head", bis={name="Sanctified Frost Witch\'s Faceguard",ilvl=277}},
        {slot="Neck", bis={name="Sindragosa\'s Cruel Claw",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Frost Witch\'s Shoulderguards",ilvl=277}},
        {slot="Back", bis={name="Shadowvault Slayer\'s Cloak",ilvl=277}},
        {slot="Chest", bis={name="Sanctified Frost Witch\'s Chestguard",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}, alt={name="Scourge Hunter\'s Vambraces",ilvl=277}},
        {slot="Hands", bis={name="Anub\'ar Stalker\'s Gloves",ilvl=277}},
        {slot="Waist", bis={name="Nerub\'ar Stalker\'s Cord",ilvl=277}},
        {slot="Legs", bis={name="Sanctified Frost Witch\'s War-Kilt",ilvl=277}},
        {slot="Feet", bis={name="Treads of the Wasteland",ilvl=277}},
        {slot="Ring", bis={name="Band of the Bone Colossus",ilvl=277}, alt={name="Signet of Twilight",ilvl=284}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Trinket", bis={name="Deathbringer\'s Will",ilvl=277}, alt={name="Herkuml War Token",ilvl=264}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}, alt={name="Tiny Abomination in a Jar",ilvl=277}},
        {slot="Main Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
        {slot="Off Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
        {slot="Totem", bis={name="Bizuri\'s Totem of Shattered Ice",ilvl=264}},
    },
    ["Spellhance Shaman"] = {
        {slot="Head", bis={name="Sanctified Frost Witch\'s Faceguard",ilvl=277}},
        {slot="Neck", bis={name="Amulet of the Silent Eulogy",ilvl=277}},
        {slot="Shoulders", bis={name="Sanctified Frost Witch\'s Shoulderguards",ilvl=277}},
        {slot="Back", bis={name="Cloak of Burning Dusk",ilvl=284}},
        {slot="Chest", bis={name="Sanctified Frost Witch\'s Chestguard",ilvl=277}},
        {slot="Wrist", bis={name="Umbrage Armbands",ilvl=284}},
        {slot="Hands", bis={name="Anub\'ar Stalker\'s Gloves",ilvl=277}},
        {slot="Waist", bis={name="Split Shape Belt",ilvl=284}},
        {slot="Legs", bis={name="Sanctified Frost Witch\'s War-Kilt",ilvl=277}},
        {slot="Feet", bis={name="Treads of the Wasteland",ilvl=277}},
        {slot="Ring", bis={name="Signet of Twilight",ilvl=284}},
        {slot="Ring", bis={name="Ashen Band of Endless Vengeance",ilvl=277}},
        {slot="Trinket", bis={name="Charred Twilight Scale",ilvl=284}},
        {slot="Trinket", bis={name="Sharpened Twilight Scale",ilvl=284}, alt={name="Phylactery of the Nameless Lich",ilvl=277}},
        {slot="Main Hand", bis={name="Royal Scepter of Terenas II",ilvl=284}},
        {slot="Off Hand", bis={name="Havoc\'s Call, Blade of Lordaeron Kings",ilvl=284}},
        {slot="Totem", bis={name="Bizuri\'s Totem of Shattered Ice",ilvl=264}},
    },
}
